spring:
  redis:
    cluster:
      nodes: "172.20.6.21:8000,172.20.6.21:8001,172.20.6.22:8002,172.20.6.22:8003,172.20.6.23:8004,172.20.6.23:8005"
      max-redirects: 6

config:
  mask:
    filter:
      fields: loginPwd

druid:
  filters: stat
  initialSize: 15
  maxActive: 20
  maxWait: 60000

master:
  jdbc:
    driverClass: oracle.jdbc.driver.OracleDriver
    password: $ENC1Zj68XXLa7swl7Tw
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.20.6.22)(PORT=1521))(LOAD_BALANCE=YES)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=mpos)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=2)(DELAY=3))))
    user: crm_user

slave:
  jdbc:
    driverClass: oracle.jdbc.driver.OracleDriver
    password: $ENC1Zj68XXLa7swl7Tw
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.20.21.67)(PORT=1521))(LOAD_BALANCE=YES)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=mpos)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)(RETRIES=2)(DELAY=3))))
    user: crm_user

activeqm:
  broker.url: failover://(tcp://172.20.6.22:61601)
  username: admin
  password: admin
  sessionCacheSize: 100

redis:
  cluster:
    address: 172.20.6.21:8000,172.20.6.21:8001,172.20.6.22:8002,172.20.6.22:8003,172.20.6.23:8004,172.20.6.23:8005
    maxRedirections: 6
    timeout: 300000

thrift:
  maxDataSize: 20000000
  connectTimeout: 10000
  socketTimeout: 10000
  timeout: 10000

zk:
  register: 172.20.11.100:2181
  register.connectionTimeout: 3000
  register.sessionTimeout: 50000
  auth:
    node: /auth/auth_server
    orgCode: 100024
    merNo: JQ1000245100061
  globalSequence: /global_sequence
  posp:
    user:
      node: /posp/user-encrypt
  partner:
    query:
      node: partner-query-api

open:
  platform:
    security: /openplatform/security_service

jlpay:
  security:
    crypto: /posp/crypto_svc

development:
  mode: true

fastdfs:
  view:
    server:
      ip:
        region-kx: 172.20.5.155
        region-ks: 172.20.5.155
      port:
        region-kx: 80
        region-ks: 80
